package com.web.cementerio.pojo.annotations;

// Generated 26/07/2012 03:22:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Cotpersona generated by hbm2java
 */
@Entity
@Table(name = "cotpersona")
public class Cotpersona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2069293345548166597L;
	private int idpersona;
	private Cottipoidentificacion cottipoidentificacion;
	private Setestado setestado;
	private Setusuario setusuario;
	private String apellido1;
	private String apellido2;
	private String nombre1;
	private String nombre2;
	private String alias;
	private Date fecharegistro;
	private String iplog;
	private String numeroidentificacion;
	private Date fechanacimiento;
	private String telefono;
	private String direccion;
	private String email;
	private String ruta;
	private byte[] objeto;
	private Integer sexo;
//	private Set<Setusuario> setusuarios = new HashSet<Setusuario>(0);
//	private Set<Petcomision> petcomisions = new HashSet<Petcomision>(0);
//	private Set<Petmascota> petmascotas = new HashSet<Petmascota>(0);

	public Cotpersona() {
	}

	public Cotpersona(int idpersona, String apellido1, String nombre1,
			Date fecharegistro, String telefono) {
		this.idpersona = idpersona;
		this.apellido1 = apellido1;
		this.nombre1 = nombre1;
		this.fecharegistro = fecharegistro;
		this.telefono = telefono;
	}

	public Cotpersona(int idpersona,
			Cottipoidentificacion cottipoidentificacion, Setestado setestado,
			Setusuario setusuario, String apellido1, String apellido2,
			String nombre1, String nombre2, String alias, Date fecharegistro,
			String iplog, String numeroidentificacion, Date fechanacimiento,
			String telefono, String direccion, String email, String ruta, byte[] objeto, Integer sexo/*, Set<Setusuario> setusuarios,
			Set<Petmascota> petmascotas, Set<Petcomision> petcomisions*/) {
		this.idpersona = idpersona;
		this.cottipoidentificacion = cottipoidentificacion;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.nombre1 = nombre1;
		this.nombre2 = nombre2;
		this.alias = alias;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.numeroidentificacion = numeroidentificacion;
		this.fechanacimiento = fechanacimiento;
		this.telefono = telefono;
		this.direccion = direccion;
		this.email = email;
		this.ruta = ruta;
		this.objeto = objeto;
		this.sexo = sexo;
//		this.setusuarios = setusuarios;
//		this.petcomisions = petcomisions;
//		this.petmascotas = petmascotas;
	}

	@Id
	@Column(name = "idpersona", unique = true, nullable = false)
	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipoidentificacion")
	public Cottipoidentificacion getCottipoidentificacion() {
		return this.cottipoidentificacion;
	}

	public void setCottipoidentificacion(
			Cottipoidentificacion cottipoidentificacion) {
		this.cottipoidentificacion = cottipoidentificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "apellido1", nullable = false, length = 30)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 30)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "nombre1", nullable = false, length = 30)
	public String getNombre1() {
		return this.nombre1;
	}

	public void setNombre1(String nombre1) {
		this.nombre1 = nombre1;
	}

	@Column(name = "nombre2", length = 30)
	public String getNombre2() {
		return this.nombre2;
	}

	public void setNombre2(String nombre2) {
		this.nombre2 = nombre2;
	}

	@Column(name = "alias", length = 30)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@Column(name = "numeroidentificacion", length = 15)
	public String getNumeroidentificacion() {
		return this.numeroidentificacion;
	}

	public void setNumeroidentificacion(String numeroidentificacion) {
		this.numeroidentificacion = numeroidentificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechanacimiento", length = 29)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "telefono", nullable = false, length = 50)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "direccion", length = 250)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ruta", length = 100)
	public String getRuta() {
		return ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}
	
	@Column(name = "objeto")
	public byte[] getObjeto() {
		return this.objeto;
	}

	public void setObjeto(byte[] objeto) {
		this.objeto = objeto;
	}
	
	@Column(name = "sexo")
	public Integer getSexo() {
		return this.sexo;
	}

	public void setSexo(Integer sexo) {
		this.sexo = sexo;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotpersona", targetEntity = Setusuario.class)
	public Set<Setusuario> getSetusuarios() {
		return this.setusuarios;
	}

	public void setSetusuarios(Set<Setusuario> setusuarios) {
		this.setusuarios = setusuarios;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotpersona", targetEntity = Petcomision.class)
	public Set<Petcomision> getPetcomisions() {
		return this.petcomisions;
	}

	public void setPetcomisions(Set<Petcomision> petcomisions) {
		this.petcomisions = petcomisions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotpersona", targetEntity = Petmascota.class)
	public Set<Petmascota> getPetmascotas() {
		return this.petmascotas;
	}

	public void setPetmascotas(Set<Petmascota> petmascotas) {
		this.petmascotas = petmascotas;
	}
*/
}
