package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petencuestacasilla generated by hbm2java
 */
@Entity
@Table(name = "petencuestacasilla")
public class Petencuestacasilla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5147900069583305654L;
	private int idencuestacasilla;
	private Setestado setestado;
	private Setusuario setusuario;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private Set<?> petplantillaencuestadetcasillas = new HashSet<Object>(0);

	public Petencuestacasilla() {
	}

	public Petencuestacasilla(int idencuestacasilla, Date fecharegistro) {
		this.idencuestacasilla = idencuestacasilla;
		this.fecharegistro = fecharegistro;
	}

	public Petencuestacasilla(int idencuestacasilla, Setestado setestado,
			Setusuario setusuario, String nombre, String descripcion,
			Date fecharegistro, String iplog,
			Set<?> petplantillaencuestadetcasillas) {
		this.idencuestacasilla = idencuestacasilla;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.petplantillaencuestadetcasillas = petplantillaencuestadetcasillas;
	}

	@Id
	@Column(name = "idencuestacasilla", unique = true, nullable = false)
	public int getIdencuestacasilla() {
		return this.idencuestacasilla;
	}

	public void setIdencuestacasilla(int idencuestacasilla) {
		this.idencuestacasilla = idencuestacasilla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petencuestacasilla", targetEntity=Petplantillaencuestadetcasilla.class)
	public Set<?> getPetplantillaencuestadetcasillas() {
		return this.petplantillaencuestadetcasillas;
	}

	public void setPetplantillaencuestadetcasillas(
			Set<?> petplantillaencuestadetcasillas) {
		this.petplantillaencuestadetcasillas = petplantillaencuestadetcasillas;
	}

}
