package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petespecie generated by hbm2java
 */
@Entity
@Table(name = "petespecie")
public class Petespecie implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 509614909806175134L;
	private int idespecie;
	private Setestado setestado;
	private Setusuario setusuario;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private Set<?> petmascotahomenajes = new HashSet<Object>(0);

	public Petespecie() {
	}

	public Petespecie(int idespecie, String nombre, Date fecharegistro) {
		this.idespecie = idespecie;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
	}

	public Petespecie(int idespecie, Setestado setestado,
			Setusuario setusuario, String nombre, String descripcion,
			Date fecharegistro, String iplog, Set<?> petmascotahomenajes) {
		this.idespecie = idespecie;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.petmascotahomenajes = petmascotahomenajes;
	}

	@Id
	@Column(name = "idespecie", unique = true, nullable = false)
	public int getIdespecie() {
		return this.idespecie;
	}

	public void setIdespecie(int idespecie) {
		this.idespecie = idespecie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petespecie", targetEntity=Petmascotahomenaje.class)
	public Set<?> getPetmascotahomenajes() {
		return this.petmascotahomenajes;
	}

	public void setPetmascotahomenajes(Set<?> petmascotahomenajes) {
		this.petmascotahomenajes = petmascotahomenajes;
	}

	@Override
	protected Object clone() throws CloneNotSupportedException{
		Petespecie petespecie = (Petespecie)super.clone();
		return petespecie;
	}
	public Petespecie clonar() throws Exception{
		return (Petespecie)this.clone();
	}
}
