package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petplantillaencuesta generated by hbm2java
 */
@Entity
@Table(name = "petplantillaencuesta")
public class Petplantillaencuesta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7324148167366704501L;
	private int idplantillaencuesta;
	private Setestado setestado;
	private Setusuario setusuario;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private Set<?> petplantillaencuestadets = new HashSet<Object>(0);
	private Set<?> petplantillaencuestagrupos = new HashSet<Object>(0);
	private Set<?> petplantillaencuestadetcasillas = new HashSet<Object>(0);

	public Petplantillaencuesta() {
	}

	public Petplantillaencuesta(int idplantillaencuesta, Date fecharegistro) {
		this.idplantillaencuesta = idplantillaencuesta;
		this.fecharegistro = fecharegistro;
	}

	public Petplantillaencuesta(int idplantillaencuesta, Setestado setestado,
			Setusuario setusuario, String nombre, String descripcion,
			Date fecharegistro, String iplog, Set<?> petplantillaencuestadets,
			Set<?> petplantillaencuestagrupos, Set<?> petplantillaencuestadetcasillas) {
		this.idplantillaencuesta = idplantillaencuesta;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.petplantillaencuestadets = petplantillaencuestadets;
		this.petplantillaencuestagrupos = petplantillaencuestagrupos;
		this.petplantillaencuestadetcasillas = petplantillaencuestadetcasillas;
	}

	@Id
	@Column(name = "idplantillaencuesta", unique = true, nullable = false)
	public int getIdplantillaencuesta() {
		return this.idplantillaencuesta;
	}

	public void setIdplantillaencuesta(int idplantillaencuesta) {
		this.idplantillaencuesta = idplantillaencuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nombre", length = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petplantillaencuesta", targetEntity=Petplantillaencuestadet.class)
	public Set<?> getPetplantillaencuestadets() {
		return this.petplantillaencuestadets;
	}

	public void setPetplantillaencuestadets(Set<?> petplantillaencuestadets) {
		this.petplantillaencuestadets = petplantillaencuestadets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petplantillaencuesta", targetEntity=Petplantillaencuestagrupo.class)
	public Set<?> getPetplantillaencuestagrupos() {
		return this.petplantillaencuestagrupos;
	}

	public void setPetplantillaencuestagrupos(Set<?> petplantillaencuestagrupos) {
		this.petplantillaencuestagrupos = petplantillaencuestagrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petplantillaencuesta", targetEntity=Petplantillaencuestadetcasilla.class)
	public Set<?> getPetplantillaencuestadetcasillas() {
		return this.petplantillaencuestadetcasillas;
	}

	public void setPetplantillaencuestadetcasillas(
			Set<?> petplantillaencuestadetcasillas) {
		this.petplantillaencuestadetcasillas = petplantillaencuestadetcasillas;
	}

}
