package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petresultadoencuestadetalle generated by hbm2java
 */
@Entity
@Table(name = "petresultadoencuestadetalle")
public class Petresultadoencuestadetalle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -938628822898248975L;
	private int idresultadoencuestadetalle;
	private Setestado setestado;
	private Petresultadoencuesta petresultadoencuesta;
	private Petplantillaencuestadetcasilla petplantillaencuestadetcasilla;
	private Setusuario setusuario;
	private String contenido;
	private Date fecharegistro;
	private String iplog;

	public Petresultadoencuestadetalle() {
	}

	public Petresultadoencuestadetalle(int idresultadoencuestadetalle,
			Petresultadoencuesta petresultadoencuesta,
			Petplantillaencuestadetcasilla petplantillaencuestadetcasilla,
			Date fecharegistro) {
		this.idresultadoencuestadetalle = idresultadoencuestadetalle;
		this.petresultadoencuesta = petresultadoencuesta;
		this.petplantillaencuestadetcasilla = petplantillaencuestadetcasilla;
		this.fecharegistro = fecharegistro;
	}

	public Petresultadoencuestadetalle(int idresultadoencuestadetalle,
			Setestado setestado, Petresultadoencuesta petresultadoencuesta,
			Petplantillaencuestadetcasilla petplantillaencuestadetcasilla,
			Setusuario setusuario, String contenido, Date fecharegistro,
			String iplog) {
		this.idresultadoencuestadetalle = idresultadoencuestadetalle;
		this.setestado = setestado;
		this.petresultadoencuesta = petresultadoencuesta;
		this.petplantillaencuestadetcasilla = petplantillaencuestadetcasilla;
		this.setusuario = setusuario;
		this.contenido = contenido;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idresultadoencuestadetalle", unique = true, nullable = false)
	public int getIdresultadoencuestadetalle() {
		return this.idresultadoencuestadetalle;
	}

	public void setIdresultadoencuestadetalle(int idresultadoencuestadetalle) {
		this.idresultadoencuestadetalle = idresultadoencuestadetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idresultadoencuesta", nullable = false)
	public Petresultadoencuesta getPetresultadoencuesta() {
		return this.petresultadoencuesta;
	}

	public void setPetresultadoencuesta(
			Petresultadoencuesta petresultadoencuesta) {
		this.petresultadoencuesta = petresultadoencuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idplantillaencuestadetallecasilla", nullable = false)
	public Petplantillaencuestadetcasilla getPetplantillaencuestadetcasilla() {
		return this.petplantillaencuestadetcasilla;
	}

	public void setPetplantillaencuestadetcasilla(
			Petplantillaencuestadetcasilla petplantillaencuestadetcasilla) {
		this.petplantillaencuestadetcasilla = petplantillaencuestadetcasilla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "contenido", length = 500)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
