package com.web.cementerio.pojo.annotations;

// Generated 26/07/2012 03:22:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petraza generated by hbm2java
 */
@Entity
@Table(name = "petraza")
public class Petraza implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5447534948211922819L;
	private int idraza;
	private Setestado setestado;
	private Setusuario setusuario;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private byte[] objeto;
	private String ruta;
	private Petespecie petespecie;
//	private Set<Petmascota> petmascotas = new HashSet<Petmascota>(0);

	public Petraza() {
	}

	public Petraza(int idraza, String nombre, Date fecharegistro) {
		this.idraza = idraza;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
	}

	public Petraza(int idraza, Setestado setestado, Setusuario setusuario,
			String nombre, String descripcion, Date fecharegistro,
			String iplog, byte[] objeto, String ruta,Petespecie petespecie/*, Set<Petmascota> petmascotas*/) {
		this.idraza = idraza;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.objeto = objeto;
		this.ruta = ruta;
		this.petespecie = petespecie;
//		this.petmascotas = petmascotas;
	}

	@Id
	@Column(name = "idraza", unique = true, nullable = false)
	public int getIdraza() {
		return this.idraza;
	}

	public void setIdraza(int idraza) {
		this.idraza = idraza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}
	
	@Column(name = "objeto")
	public byte[] getObjeto() {
		return this.objeto;
	}

	public void setObjeto(byte[] objeto) {
		this.objeto = objeto;
	}

	@Column(name = "ruta", length = 100)
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petraza", targetEntity = Petmascota.class)
	public Set<Petmascota> getPetmascotas() {
		return this.petmascotas;
	}

	public void setPetmascotas(Set<Petmascota> petmascotas) {
		this.petmascotas = petmascotas;
	}
*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idespecie")
	public Petespecie getPetespecie() {
		return petespecie;
	}

	public void setPetespecie(Petespecie petespecie) {
		this.petespecie = petespecie;
	}
}
