package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petresultadoencuesta generated by hbm2java
 */
@Entity
@Table(name = "petresultadoencuesta")
public class Petresultadoencuesta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2854211212355860276L;
	private int idresultadoencuesta;
	private Setestado setestado;
	private Setusuario setusuario;
	private String nroidentificacion;
	private Integer tipoidentificacion;
	private String nombres;
	private String nombremascota;
	private Date fecharegistro;
	private String iplog;
	private Set<?> petresultadoencuestadetalles = new HashSet<Object>(0);

	public Petresultadoencuesta() {
	}

	public Petresultadoencuesta(int idresultadoencuesta, Date fecharegistro) {
		this.idresultadoencuesta = idresultadoencuesta;
		this.fecharegistro = fecharegistro;
	}

	public Petresultadoencuesta(int idresultadoencuesta, Setestado setestado,
			Setusuario setusuario, String nroidentificacion,
			Integer tipoidentificacion, String nombres, String nombremascota,
			Date fecharegistro, String iplog, Set<?> petresultadoencuestadetalles) {
		this.idresultadoencuesta = idresultadoencuesta;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.nroidentificacion = nroidentificacion;
		this.tipoidentificacion = tipoidentificacion;
		this.nombres = nombres;
		this.nombremascota = nombremascota;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.petresultadoencuestadetalles = petresultadoencuestadetalles;
	}

	@Id
	@Column(name = "idresultadoencuesta", unique = true, nullable = false)
	public int getIdresultadoencuesta() {
		return this.idresultadoencuesta;
	}

	public void setIdresultadoencuesta(int idresultadoencuesta) {
		this.idresultadoencuesta = idresultadoencuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nroidentificacion", length = 15)
	public String getNroidentificacion() {
		return this.nroidentificacion;
	}

	public void setNroidentificacion(String nroidentificacion) {
		this.nroidentificacion = nroidentificacion;
	}

	@Column(name = "tipoidentificacion")
	public Integer getTipoidentificacion() {
		return this.tipoidentificacion;
	}

	public void setTipoidentificacion(Integer tipoidentificacion) {
		this.tipoidentificacion = tipoidentificacion;
	}

	@Column(name = "nombres", length = 150)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "nombremascota", length = 100)
	public String getNombremascota() {
		return this.nombremascota;
	}

	public void setNombremascota(String nombremascota) {
		this.nombremascota = nombremascota;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petresultadoencuesta", targetEntity=Petresultadoencuestadetalle.class)
	public Set<?> getPetresultadoencuestadetalles() {
		return this.petresultadoencuestadetalles;
	}

	public void setPetresultadoencuestadetalles(Set<?> petresultadoencuestadetalles) {
		this.petresultadoencuestadetalles = petresultadoencuestadetalles;
	}

}
