package com.web.cementerio.pojo.annotations;

// Generated 05/03/2014 11:20:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Setmenu generated by hbm2java
 */
@Entity
@Table(name = "setmenu")
public class Setmenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8484926865724041657L;
	private int idmenu;
	private Setestado setestado;
	private Setusuario setusuario;
	private String nombre;
	private String descripcion;
	private Integer idmenupadre;
	private Integer nivel;
	private String iconourl;
	private String paginaurl;
	private Integer orden;
	private Date fecharegistro;
	private String iplog;

	public Setmenu() {
	}

	public Setmenu(int idmenu, Date fecharegistro) {
		this.idmenu = idmenu;
		this.fecharegistro = fecharegistro;
	}

	public Setmenu(int idmenu, Setestado setestado, Setusuario setusuario,
			String nombre, String descripcion, Integer idmenupadre,
			Integer nivel, String iconourl, String paginaurl, Integer orden,
			Date fecharegistro, String iplog) {
		this.idmenu = idmenu;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.idmenupadre = idmenupadre;
		this.nivel = nivel;
		this.iconourl = iconourl;
		this.paginaurl = paginaurl;
		this.orden = orden;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idmenu", unique = true, nullable = false)
	public int getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(int idmenu) {
		this.idmenu = idmenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "idmenupadre")
	public Integer getIdmenupadre() {
		return this.idmenupadre;
	}

	public void setIdmenupadre(Integer idmenupadre) {
		this.idmenupadre = idmenupadre;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "iconourl", length = 100)
	public String getIconourl() {
		return this.iconourl;
	}

	public void setIconourl(String iconourl) {
		this.iconourl = iconourl;
	}

	@Column(name = "paginaurl", length = 200)
	public String getPaginaurl() {
		return this.paginaurl;
	}

	public void setPaginaurl(String paginaurl) {
		this.paginaurl = paginaurl;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
