package com.web.cementerio.pojo.annotations;

// Generated 31/05/2014 05:26:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * Setpeticionclave generated by hbm2java
 */
@Entity
@Table(name = "setpeticionclave")
public class Setpeticionclave implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7843738631518841869L;
	private int idpeticionclave;
	private String usuario;
	private UUID uid;
	private Date fechaexpiracion;
	private Date fecharegistro;
	private String iplog;

	public Setpeticionclave() {
	}

	public Setpeticionclave(int idpeticionclave, String usuario,
			UUID uid, Date fechaexpiracion, Date fecharegistro) {
		this.idpeticionclave = idpeticionclave;
		this.usuario = usuario;
		this.uid = uid;
		this.fechaexpiracion = fechaexpiracion;
		this.fecharegistro = fecharegistro;
	}

	public Setpeticionclave(int idpeticionclave, String usuario,
			UUID uid, Date fechaexpiracion, Date fecharegistro,
			String iplog) {
		this.idpeticionclave = idpeticionclave;
		this.usuario = usuario;
		this.uid = uid;
		this.fechaexpiracion = fechaexpiracion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idpeticionclave", unique = true, nullable = false)
	public int getIdpeticionclave() {
		return this.idpeticionclave;
	}

	public void setIdpeticionclave(int idpeticionclave) {
		this.idpeticionclave = idpeticionclave;
	}

	@Column(name = "usuario", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "uid", nullable = false)
	//@Type(type="pg-uuid")
	@Type(type="uuid-char")
	public UUID getUid() {
		return this.uid;
	}

	public void setUid(UUID uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaexpiracion", nullable = false, length = 29)
	public Date getFechaexpiracion() {
		return this.fechaexpiracion;
	}

	public void setFechaexpiracion(Date fechaexpiracion) {
		this.fechaexpiracion = fechaexpiracion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
